color: sky
description: null
fieldLayouts:
  50af9c16-3cb9-4994-b8b7-1dea6371c5f1:
    cardThumbAlignment: end
    cardView:
      - parent
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-30T19:20:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ff8f529f-79cf-4f8b-af51-dc2679bea708 # Button Link
            handle: buttonLink
            includeInCards: false
            instructions: null
            label: 'Link knop'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2525b4e-db34-4d06-93e2-f2b64288aecb
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-17T19:33:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0448039b-68a3-4865-a28b-24d17f5f6a5c # Button Download
            handle: null
            includeInCards: false
            instructions: null
            label: 'Download knop'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfcea9a1-0f66-4943-ba4b-41df2875d642
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 4ef4aad5-5543-4c2e-abb9-fadc576f34ec
        userCondition: null
handle: buttonSet
hasTitleField: false
icon: arrows-turn-right
name: 'Button Set'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
