color: null
description: null
fieldLayouts:
  8453ae5b-8400-4270-bbed-11d653d698c2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-17T18:44:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Paginatitel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 66c2d026-70a3-475e-8e67-3483102953cc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T18:49:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: intro
            includeInCards: false
            instructions: null
            label: Introductie
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 641a488a-d502-4aad-9b5c-9a0d58592cfa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T18:49:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
            handle: null
            includeInCards: false
            instructions: null
            label: Afbeelding
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab567294-a8e2-4c81-9062-668aa4f20d37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T18:49:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b61a538-af28-46cf-b884-bb22dc1821ca # SEO Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd0b706f-0672-4db9-a8d6-7d73de47d0ba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d8569f6-81f8-4339-a8ab-3cc4dbff2a0b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T19:12:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bedcd512-47d2-4bf6-b77b-fa82d8d107cf # Content blokken
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d4c5741-52e6-476a-a39b-e8f626c57ba7
            userCondition: null
            warning: null
            width: 100
        name: 'Content blokken'
        uid: 4dd82199-cf46-4851-b280-2e2fe3f45d61
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T18:58:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 208c80f3-341d-4a5b-9070-3fa5f9c2152d # Tarievenlijst
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd0ef362-76d8-4730-9e4f-4191c72a7ebc
            userCondition: null
            warning: null
            width: 100
        name: Tarievenlijst
        uid: 8fcc5938-b644-4a85-8437-c8e4527cc4ce
        userCondition: null
handle: congrescentrum
hasTitleField: true
icon: people-roof
name: Congrescentrum
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
