color: null
description: null
fieldLayouts:
  6b03d60c-97fa-464c-9b0e-5fbf7aac402e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-17T16:18:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Paginatitel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 28ac318c-23ea-4442-999c-8ef9cd164ee6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-18T09:49:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 83db36ef-e67b-4f25-971a-ebc7ec0dea3e # Plain Text
            handle: payoff
            includeInCards: false
            instructions: null
            label: Payoff
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e5fd18d-854f-41ac-9aa8-5fcd0b561ce9
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-17T16:22:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
            handle: headerImage
            includeInCards: false
            instructions: null
            label: 'Afbeelding '
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a53e2877-782f-4e6c-b951-e80bf6cc1cfd
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-17T18:20:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b61a538-af28-46cf-b884-bb22dc1821ca # SEO Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 788e8a69-3461-4122-8199-084cec0adb63
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: fa711690-b214-4970-8440-701ebeebcf98
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T16:22:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: aboutText
            includeInCards: false
            instructions: null
            label: Tekst
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0b2ef55-d783-45a0-ab6f-70d9ba1a906c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T16:22:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
            handle: aboutImage
            includeInCards: false
            instructions: null
            label: Afbeelding
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9965a2be-80cf-47b7-98f0-1210090295c1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-17T16:30:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 86b4bc13-5cc4-482a-ba3d-a1200f77f0c5 # Select Entry
            handle: aboutLink
            includeInCards: false
            instructions: null
            label: 'Lees meer link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5f50abb-06f0-4d35-b3ab-76ae38ce540b
            userCondition: null
            warning: null
            width: 25
        name: 'Over ons'
        uid: 81281b2a-10b9-4d5a-9fc8-5eefc34ca0f5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T17:52:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 22c4f459-ab44-47f3-ab5c-f64535cc5509 # Diensten [TEST]
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c9eaa10-bc92-45d6-b3cb-4e449b57e265
            userCondition: null
            warning: null
            width: 100
        name: test
        uid: bb09c076-69f5-4a7d-b2e3-f2a30830aba9
        userCondition: null
handle: homepage
hasTitleField: true
icon: house-window
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
