color: null
description: null
fieldLayouts:
  77fcabc0-0dd6-45a4-8321-97f8dd4f42b2:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:8af91632-faba-42d8-aebc-73773e79644c'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-18T07:46:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Partnernaam
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2f7107d1-c97e-40a9-a7c2-c4294bac2df0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T20:20:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 884dd8a2-8ede-4a60-af46-769c69dfa8d4 # Externe URL
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8af91632-faba-42d8-aebc-73773e79644c
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-17T20:24:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8c4d9ab3-2305-4b12-b68f-3c1cad72d49a # Assets Partnerlogo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8f7d56a-0acb-42b9-b1ea-dbe2395cb222
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 05bd6112-bc9c-4cbd-b808-41f7334c9abb
        userCondition: null
handle: partnerlink
hasTitleField: true
icon: link
name: Partnerlink
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
