color: null
description: 'Alleen gebruiken voor het ruimtes overzicht'
fieldLayouts:
  c151489f-d362-4e4f-9513-0de89b7a3484:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:490380ab-369b-4dba-9ab7-6d903b59d1af'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-01T20:34:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 50ef226f-701d-407e-8f54-d132c5ac095f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-01T20:38:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: null
            includeInCards: true
            instructions: null
            label: Omschrijving
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 490380ab-369b-4dba-9ab7-6d903b59d1af
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-10-01T20:38:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8235d94d-82ef-4fb0-ae36-807b331b730a # Assets Image
            handle: null
            includeInCards: false
            instructions: null
            label: Afbeelding
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 331a2711-b53f-49d4-873c-35ce6bce4ffc
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 3f07ab75-0b35-4592-82b1-9683aa21825b
        userCondition: null
handle: ruimtes
hasTitleField: true
icon: hotel
name: Ruimtes
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
