color: null
description: null
fieldLayouts:
  205183bd-2fe6-46f8-9626-93affd5cb085:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T18:53:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 83db36ef-e67b-4f25-971a-ebc7ec0dea3e # Plain Text
            handle: description
            includeInCards: false
            instructions: null
            label: 'Ruimte en dagdeel'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 690f374f-d369-42ae-947e-0dbc2e15023e
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-17T18:53:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 233fda5c-b05d-4f02-99af-20045ba42e31 # Prijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a1d425e-80ce-4d11-8aec-06e2967f71a2
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 8989b81d-fc16-4524-96db-ab6966e3ef0e
        userCondition: null
handle: tarieven
hasTitleField: false
icon: list
name: Tarieven
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
