baseUrl: $CURSUS_NATTE_TEELTEN_URL
enabled: '1'
handle: cursusNatteTeelten
hasUrls: true
language: nl
name: 'Cursus natte teelten'
primary: false
siteGroup: 7db4c8c9-64ae-4f55-9955-8ec3059fb9d1 # Biosintrum
sortOrder: 2
