altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  252a0faa-d945-46b0-a354-bc65a2cab160:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-17T19:07:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7d21a158-c41d-46a6-943b-d986986208c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T19:08:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b378d7b8-6042-489d-b53d-727c66711509 # Assets Download
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1352dcbd-08e2-446a-b0e6-62a9a7444ad0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 460a0910-05d2-494c-8dea-c5e3d812ccaa
        userCondition: null
fs: localStorage
handle: downloads
name: Downloads
sortOrder: 3
subpath: downloads
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
