altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8477d36c-5ee9-4a11-ba1f-a0a094b4b81c:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-17T15:36:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 92fd4a82-e8f6-4fac-b98c-ffdeb7f62c4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T15:48:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4f212a46-d489-4335-ae26-73116a6a1228 # Assets Embed
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42413ffb-a292-4984-b6b4-e86a9cf68f8a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8d7823f5-654b-400c-a32f-9f198839eae2
        userCondition: null
fs: localStorage
handle: embeds
name: Embeds
sortOrder: 2
subpath: embeds
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
