fieldLayouts:
  bebc2b25-3516-4c67-8d00-7193b3a3985d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T17:41:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 83db36ef-e67b-4f25-971a-ebc7ec0dea3e # Plain Text
            handle: bookingTitle
            includeInCards: false
            instructions: null
            label: Titel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e4105a9-0b46-41d2-b0c9-f6f8a4030bdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T17:41:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: bookingText
            includeInCards: false
            instructions: null
            label: Tekst
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 124badb9-14e7-409b-a7ca-7c12f436f0dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T17:41:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 86b4bc13-5cc4-482a-ba3d-a1200f77f0c5 # Select Entry
            handle: null
            includeInCards: false
            instructions: null
            label: 'Pagina link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4fc4edd-2bed-4a3d-9513-3bfb42ee0526
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-18T16:20:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 85805eae-f505-419b-bfcc-0d9b6e607873 # Assets Global Image
            handle: bookingImage
            includeInCards: false
            instructions: null
            label: Afbeelding
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0443f3ea-049b-4089-a316-e463d6ce0fca
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 7c59d5bd-32f1-43ff-9736-e4318b9be355
        userCondition: null
handle: blokReserveren
name: 'Blok Reserveren'
sortOrder: 4
