fieldLayouts:
  4e7953a3-a64f-42c7-a632-6cbf46a69d59:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-05T19:12:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 83db36ef-e67b-4f25-971a-ebc7ec0dea3e # Plain Text
            handle: tarievenlijstHeader
            includeInCards: false
            instructions: null
            label: Titel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aba54ad-9467-4ad9-a5c4-ff4fa1ede4ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-05T19:11:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 15ccb303-9172-4a05-82fb-a3f2ac94efa1 # Dagdeel en prijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 399773b2-bc6f-41b9-a879-0599ecbfbefc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-05T19:11:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3fbba55-9047-45a2-9bdd-0013a9b83f23 # Rich Text
            handle: tarievenlijstFooter
            includeInCards: false
            instructions: null
            label: 'Footer tekst'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f5a90da-3fbb-4203-87c3-cb867d4e2a1c
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-10-05T19:11:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b378d7b8-6042-489d-b53d-727c66711509 # Assets Download
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91151379-da4c-4a98-ba6c-99b38a99b602
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 934e62b7-3b02-4d22-8000-c48d05e3d454
        userCondition: null
handle: tarievenlijst
name: Tarievenlijst
sortOrder: 5
