defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 5bb3cb31-9529-4f7b-b407-bee0476b98df # Actueel
handle: agenda
maxAuthors: 1
name: Agenda
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fb0d368d-2fb7-4027-a060-679959808366: # Biosintrum
    enabledByDefault: true
    hasUrls: true
    template: actueel/_entry.twig
    uriFormat: 'agenda/{slug}'
type: channel
