defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 4acbf173-f5b9-48c3-8ffb-906f3a57a3ce # Paginas
handle: cursusNatteTeelten
maxAuthors: 1
name: 'Cursus natte teelten'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  af50c774-c285-4afd-a496-c976e435b15d: # Cursus natte teelten
    enabledByDefault: true
    hasUrls: true
    template: cursusNatteTeelten/_entry.twig
    uriFormat: __home__
type: single
